<a href="https://colab.research.google.com/github/21PA1A6132/dwm-lab/blob/main/dwm_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1-D array
import numpy as np
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [7]:
#array of numbers from 10 to 100 with interval of 
x=np.arange(10,100,5)
print(x)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [30]:
#Random elements array with size 10
x=(np.random.random(10)*100).astype(int)
print(x)x=(np.random.random(10)*100).astype(int)

[56 74 11 26 17 10 14  6 75 60]


In [11]:
#2-D array
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [12]:
#Adding elements at end
x=np.array([1,2,3])
print("Before appending array is:",x)
x=np.append(x,[4,5])
print("After appending array is:",x)

Before appending array is: [1 2 3]
After appending array is: [1 2 3 4 5]


In [14]:
#Adding elements at a particular index
x=np.array([1,2,4])
print("Before inserting array is:",x)
x=np.insert(x,2,3)
print("After inserting array is:",x)

Before inserting array is: [1 2 4]
After inserting array is: [1 2 3 4]


In [38]:
#removing elements
a=np.array([1,2,3,4,5])
print("before deletion array is:",a)
a=np.delete(a,3)
print("After deletion array is:",a)

before deletion array is: [1 2 3 4 5]
After deletion array is: [1 2 3 5]


In [41]:
#Modifying elements 
b=np.arange(10,50,5)
b[b<20]=0
print(b)

[ 0  0 20 25 30 35 40 45]


In [43]:
#Arithmetic operations on numpy array's
a=np.array([1,2,3,4])
b=np.arange(4)
print("The elements in a are",a)
print("The elements in b are",b)
print("Result after Addition",a+b)
print("Result after substraction",a-b)
print("Result after multiplication",a*b)
print("Result after division",a/b)
print("Result after increasing the number to the power of 4",b**4)
print("Result after applying sin and multiplying with 10",10*np.sin(a))
a[0] +=10
print("Result after adding first element with 10",a)
print(np.dot(a,b))

The elements in a are [1 2 3 4]
The elements in b are [0 1 2 3]
Result after Addition [1 3 5 7]
Result after substraction [1 1 1 1]
Result after multiplication [ 0  2  6 12]
Result after division [       inf 2.         1.5        1.33333333]
Result after increasing the number to the power of 4 [ 0  1 16 81]
Result after applying sin and multiplying with 10 [ 8.41470985  9.09297427  1.41120008 -7.56802495]
Result after adding first element with 10 [11  2  3  4]
20


<ipython-input-43-c707be142944>:9: RuntimeWarning: divide by zero encountered in true_divide
  print("Result after division",a/b)


In [ ]:
#Slicing a 1D aray


In [46]:
a=np.arange(10)**3
print("Let's consider the elements",a)
print("The output of a[2] is", a[2])
print("The output of a[2:4] is",a[2:4])
print("The output of a[2:3] is",a[2:3])
print("The output of a[-1] is",a[-1])
print("The output of a[-2] is",a[-2]) 
print("The output of a[-5:-2] is",a[-5:-2]) 

Let's consider the elements [  0   1   8  27  64 125 216 343 512 729]
The output of a[2] is 8
The output of a[2:4] is [ 8 27]
The output of a[2:3] is [8]
The output of a[-1] is 729
The output of a[-2] is 512
The output of a[-5:-2] is [125 216 343]


In [47]:
# Slicing a 2-D array
a=np.arange(12).reshape(4,3)**2 
11.
print("The output of a[2] is",a)
print("The output of a[1:3] is",a[1:3]) 
print("The output of a[1:3,1:2] is",a[1:3,1:2])
print("The output of a[2,] is",a[2,])
print("The output of a[:3,] is",a[:3,])
print("The output of a[-1,] is",a[-1,])
print("The output of a[-1,-1] is",a[-1,-1]) 

The output of a[2] is [[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]
The output of a[1:3] is [[ 9 16 25]
 [36 49 64]]
The output of a[1:3,1:2] is [[16]
 [49]]
The output of a[2,] is [36 49 64]
The output of a[:3,] is [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
The output of a[-1,] is [ 81 100 121]
The output of a[-1,-1] is 121


In [49]:
#Iterating
a=np.arange(12).reshape(4,3)**2 
print("Let's consider an array\n",a)
print("\n")
for i in a:
  print(i*2)

Let's consider an array
 [[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]


[0 2 8]
[18 32 50]
[ 72  98 128]
[162 200 242]


In [58]:
#Matrix operation
a=(np.random.random(12)*100).astype(int).reshape(3,4)
print("Let's consider a 1-D array\n",a)
print("After reshaping to 2 by 6 matrix\n",a.reshape(2,6))
print("To Flatten the array\n",a.ravel())
print("To transpose the array\n",a.T)

Let's consider a 1-D array
 [[68 35 75 46]
 [91 50 68  5]
 [ 8 46 45  8]]
After reshaping to 2 by 6 matrix
 [[68 35 75 46 91 50]
 [68  5  8 46 45  8]]
To Flatten the array
 [68 35 75 46 91 50 68  5  8 46 45  8]
To transpose the array
 [[68 91  8]
 [35 50 46]
 [75 68 45]
 [46  5  8]]
